apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventra-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - inventra-api.duckdns.org
      secretName: inventra-api-tls
  rules:
    - host: inventra-api.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: inventra-api
                port:
                  name: http
